// Database types - will be generated by Supabase CLI
// For now, we'll use these placeholder types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          phone: string | null;
          fullName: string;
          avatarUrl: string | null;
          roles: string[];
          kycStatus: string;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          email: string;
          phone?: string | null;
          fullName: string;
          avatarUrl?: string | null;
          roles?: string[];
          kycStatus?: string;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          id?: string;
          email?: string;
          phone?: string | null;
          fullName?: string;
          avatarUrl?: string | null;
          roles?: string[];
          kycStatus?: string;
          createdAt?: string;
          updatedAt?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          hostId: string;
          make: string;
          model: string;
          year: number;
          color: string;
          plateNumber: string;
          vin: string | null;
          locationLat: number;
          locationLng: number;
          locationPublicLat: number | null;
          locationPublicLng: number | null;
          city: string;
          state: string | null;
          country: string;
          address: string | null;
          description: string | null;
          basePriceDay: number;
          weekendPriceDay: number | null;
          estimatedValue: number | null;
          deliveryAvailable: boolean;
          deliveryPrice: number | null;
          status: string;
          features: string[];
          seats: number;
          transmission: string;
          fuelType: string;
          mileage: number | null;
          mileageLimit: number | null;
          suggestedPrice: number | null;
          pricingConfidence: number | null;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          hostId: string;
          make: string;
          model: string;
          year: number;
          color: string;
          plateNumber: string;
          vin?: string | null;
          locationLat: number;
          locationLng: number;
          locationPublicLat?: number | null;
          locationPublicLng?: number | null;
          city: string;
          state?: string | null;
          country?: string;
          address?: string | null;
          description?: string | null;
          basePriceDay: number;
          weekendPriceDay?: number | null;
          estimatedValue?: number | null;
          deliveryAvailable?: boolean;
          deliveryPrice?: number | null;
          status?: string;
          features?: string[];
          seats: number;
          transmission: string;
          fuelType: string;
          mileage?: number | null;
          mileageLimit?: number | null;
          suggestedPrice?: number | null;
          pricingConfidence?: number | null;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          id?: string;
          hostId?: string;
          make?: string;
          model?: string;
          year?: number;
          color?: string;
          plateNumber?: string;
          vin?: string | null;
          locationLat?: number;
          locationLng?: number;
          locationPublicLat?: number | null;
          locationPublicLng?: number | null;
          city?: string;
          state?: string | null;
          country?: string;
          address?: string | null;
          description?: string | null;
          basePriceDay?: number;
          weekendPriceDay?: number | null;
          estimatedValue?: number | null;
          deliveryAvailable?: boolean;
          deliveryPrice?: number | null;
          status?: string;
          features?: string[];
          seats?: number;
          transmission?: string;
          fuelType?: string;
          mileage?: number | null;
          mileageLimit?: number | null;
          suggestedPrice?: number | null;
          pricingConfidence?: number | null;
          createdAt?: string;
          updatedAt?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          driverId: string;
          hostId: string;
          vehicleId: string;
          startDate: string;
          endDate: string;
          baseAmount: number;
          deliveryFee: number | null;
          platformFee: number;
          depositAmount: number;
          totalAmount: number;
          status: string;
          cancelledBy: string | null;
          cancelledAt: string | null;
          cancellationReason: string | null;
          pickupLocation: string | null;
          returnLocation: string | null;
          pickupOdometer: number | null;
          returnOdometer: number | null;
          pickupPhoto: string | null;
          returnPhoto: string | null;
          pickupNotes: string | null;
          returnNotes: string | null;
          pickupAt: string | null;
          returnAt: string | null;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          driverId: string;
          hostId: string;
          vehicleId: string;
          startDate: string;
          endDate: string;
          baseAmount: number;
          deliveryFee?: number | null;
          platformFee: number;
          depositAmount: number;
          totalAmount: number;
          status?: string;
          cancelledBy?: string | null;
          cancelledAt?: string | null;
          cancellationReason?: string | null;
          pickupLocation?: string | null;
          returnLocation?: string | null;
          pickupOdometer?: number | null;
          returnOdometer?: number | null;
          pickupPhoto?: string | null;
          returnPhoto?: string | null;
          pickupNotes?: string | null;
          returnNotes?: string | null;
          pickupAt?: string | null;
          returnAt?: string | null;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          id?: string;
          driverId?: string;
          hostId?: string;
          vehicleId?: string;
          startDate?: string;
          endDate?: string;
          baseAmount?: number;
          deliveryFee?: number | null;
          platformFee?: number;
          depositAmount?: number;
          totalAmount?: number;
          status?: string;
          cancelledBy?: string | null;
          cancelledAt?: string | null;
          cancellationReason?: string | null;
          pickupLocation?: string | null;
          returnLocation?: string | null;
          pickupOdometer?: number | null;
          returnOdometer?: number | null;
          pickupPhoto?: string | null;
          returnPhoto?: string | null;
          pickupNotes?: string | null;
          returnNotes?: string | null;
          pickupAt?: string | null;
          returnAt?: string | null;
          createdAt?: string;
          updatedAt?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: "HOST" | "DRIVER" | "ADMIN";
      kyc_status: "PENDING" | "VERIFIED" | "REJECTED";
      vehicle_status: "DRAFT" | "PENDING_APPROVAL" | "ACTIVE" | "PAUSED" | "REJECTED";
      booking_status: "PENDING" | "CONFIRMED" | "ACTIVE" | "COMPLETED" | "CANCELLED";
      payment_status: "PENDING" | "PROCESSING" | "HELD" | "RELEASED" | "REFUNDED" | "FAILED";
    };
  };
}
